### ISSUE TITLE
Translating language keys 

### ISSUE THREAD

**Issue by julien** [liferay/liferay-ckeditor#125]
When adding language keys in plugins (usually located in a `lang` directory), these don't get translated 
(except if the developer adding those language keys is able to translate them to every language supported)

We need to find a solution to this problem.

@jbalsas [pointed out](https://github.com/mateomustapic/liferay-ckeditor/commit/d30babf7c074aef48755ed145f87a76d82856834#r41838508) that we could  re-use existing keys or copy them to our plugin's `lang` directory in the case those keys already exist

Let's also try to think of a solution when adding new keys.

**Comment by jbalsas** [comment]
> Let's also try to think of a solution when adding new keys.

Ideally we should avoid this... because we (and also CKEditor) pay translators to do this, so the best way to achieve it is through proper integration with our existing mechanisms which is not something I really want to explore for this repo...

We tried in the past with AlloyEditor and it didn't turn out so well... so our best bet is probably to:
- Avoid adding new keys
- Adding them in `liferay-portal` where we have a translation mechanism in place and then just pass them over as configuration to where they're needed
- Others...

**Comment by julien** [comment]
@jbalsas thanks for clarifying

**Comment by julien** [comment]
Closing this since it's solved.
