### ISSUE TITLE
Evaluate risks of the way we build using plugins and skins

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-ckeditor#157]
Haven't done a release in the while, but while cutting [v4.14.1-liferay.19](https://github.com/liferay/liferay-ckeditor/releases/tag/v4.14.1-liferay.19) today I noticed that we have quite a few changes in the build output beyond what you would expect based on the only PR that we ([this one](https://github.com/liferay/liferay-ckeditor/pull/156)) merged since the last release.

Some examples: note how both [skins](https://github.com/liferay/liferay-ckeditor/commits/master/ckeditor/skins/moono) and [plugins](https://github.com/liferay/liferay-ckeditor/commits/master/ckeditor/plugins/scayt) change with almost every release.

I am not sure about why the skins change every time, but at least for plugins, you can see [we download whatever the latest version is during `./ck.sh setup`](https://github.com/liferay/liferay-ckeditor/blob/fe0e9f92e96f7bc9e8bce836abf53675eb39a097/ck.sh#L279-L280). This is kind of necessary: people _do_ have to "freshen" their repo before running `./ck.sh build`, but it definitely increases our risk profile — we might want to ship a one-line patch, but we actually ship that patch plus whatever-changed-in-plugins-and-skins-since-last-time as well.

So this ticket is just to flag the risk here and note that we might want to do something about it (like "freezing" these resources inside the repo instead of downloading them). I am pretty sure we can for those plugins, but the skins might be harder (if I had to guess, I'd bet that is happening as part of CKEditor's own build process, and that could be harder to change).

Labeling as "rfc" because it's not yet clear _what_ we will or should do about this.

**Comment by julien** [comment]
Just adding some notes here.

I noticed that the [scayt](https://ckeditor.com/cke4/addon/scayt)  and [wsc](https://ckeditor.com/cke4/addon/wsc) plugins are downloaded each time we run:  [`./ck.sh setup`](https://github.com/liferay/liferay-ckeditor/blob/429dc8a7acd0bd9cde9e3854c4d5619b370ea8d2/ck.sh#L279-L280) and [`./ck.sh update`](https://github.com/liferay/liferay-ckeditor/blob/429dc8a7acd0bd9cde9e3854c4d5619b370ea8d2/ck.sh#L383-L384).

The [wsc](https://ckeditor.com/cke4/addon/wsc) plugin, will reach its **end of life** at the end of the year:
> This plugin has an End-of-Life date set to December 31st, 2021. This means it will not be supported any longer and may stop working after this date. We strongly encourage everyone to choose one of the other available spellchecking solutions - Spell Check As You Type (SCAYT) or WProofreader.

I know that we download them because they [aren't in ckeditor4's plugin directory](https://github.com/ckeditor/ckeditor4/tree/eb2d11644a796cd13cd047cd55541430359f9317/plugins), but it might be a good time to think about an alternative: I'm no expert in U.X., but since Web Browsers have built-in spell checking (and it's pretty decent), I'm wondering  if we use that (even though CKEditor [disables it by default](https://ckeditor.com/docs/ckeditor4/latest/features/spellcheck.html))

In any case, for those two plugins, I agree that a good option would be to do what @wincent suggested which is "freezing" them  inside the repo.

Concerning the skins, I'll to investigate a bit more, but I'm open to suggestions (cc @carloslancha)
