### ISSUE TITLE
Support scss in custom skins

### ISSUE THREAD

**Issue by carloslancha** [liferay/liferay-ckeditor#68]
Right now when we create a custom skin we're copying the base skin "moono-lisa", which uses css.

For our custom moono-lexicon the ideal would be use clay variables, the question is... does it worth it?

**Comment by wincent** [comment]
I don't know. The thing about Clay variables in portal is that they are dynamically interpreted at build time via SCSS. But liferay-ckeditor is an independent project, published to NPM, and imported as a `dependency`. So, you could find a way to use Clay variables here to generate static CSS, but it still wouldn't be participating in the normal Clay variable → SCSS → CSS build flow in liferay-portal; any time we change Clay in liferay-portal, we'd have to change it here too in order for it to follow.

My gut instinct is that it's not worth it. I could be convinced otherwise, by that's the conclusion I get from 10 seconds of thinking about it.

**Comment by jbalsas** [comment]
We can keep this open, but I agree we should table this until we see real value. For now, if we get the skin going and manage to make the necessary changes, that's what we need. Chances of us heavily modifying the skin or needing heavy infra is not very likely after this...
